name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # 每次 push 到 main 分支就部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build && cp src/swagger.yaml dist/swagger.yaml && cp ecosystem.config.js dist/ecosystem.config.js

      - name: Generate .ebextensions/ssl.config with certificate
        env:
          CF_ORIGIN_CERT: ${{ secrets.CF_ORIGIN_CERT }}
          CF_ORIGIN_KEY: ${{ secrets.CF_ORIGIN_KEY }}
        run: |
          echo "CERT length: ${#CF_ORIGIN_CERT}"
          echo "KEY length: ${#CF_ORIGIN_KEY}"
          mkdir -p .ebextensions
          echo "files:" > .ebextensions/ssl.config

          echo "  \"/etc/ssl/certs/cloudflare.crt\":" >> .ebextensions/ssl.config
          echo "    mode: \"000644\"" >> .ebextensions/ssl.config
          echo "    owner: root" >> .ebextensions/ssl.config
          echo "    group: root" >> .ebextensions/ssl.config
          echo "    content: |" >> .ebextensions/ssl.config
          echo "${CF_ORIGIN_CERT}" | sed 's/^/      /' >> .ebextensions/ssl.config

          echo "" >> .ebextensions/ssl.config
          echo "  \"/etc/ssl/private/cloudflare.key\":" >> .ebextensions/ssl.config
          echo "    mode: \"000600\"" >> .ebextensions/ssl.config
          echo "    owner: root" >> .ebextensions/ssl.config
          echo "    group: root" >> .ebextensions/ssl.config
          echo "    content: |" >> .ebextensions/ssl.config
          echo "${CF_ORIGIN_KEY}" | sed 's/^/      /' >> .ebextensions/ssl.config

          echo "" >> .ebextensions/ssl.config
          echo "container_commands:" >> .ebextensions/ssl.config
          echo "  01_remove_default_conf:" >> .ebextensions/ssl.config
          echo "    command: \"rm -f /etc/nginx/conf.d/00_elastic_beanstalk_proxy.conf\"" >> .ebextensions/ssl.config
          echo "  02_restart_nginx:" >> .ebextensions/ssl.config
          echo "    command: \"service nginx restart\"" >> .ebextensions/ssl.config

      - name: Zip compiled app
        run: |
          zip -r app.zip dist package.json package-lock.json .ebextensions .platform

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: fit-tracker-backend-prod      
          environment_name: fit-tracker-backend-prod-env  
          region: ap-southeast-2                       
          version_label: v-${{ github.run_number }}-${{ github.sha }}
          deployment_package: app.zip
